# Generated by Django 3.0.2 on 2020-06-25 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eat', '0002_auto_20200609_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='quote_recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='quote_recipe',
            field=models.ManyToManyField(blank=True, related_name='quote_recipe', to=settings.AUTH_USER_MODEL, verbose_name='参考cookレシピ'),
        ),
    ]
