# Generated by Django 3.0.2 on 2020-06-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0003_auto_20200626_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quote',
            field=models.CharField(choices=[('有り', '有り'), ('無し', '無し')], default='無し', max_length=20, verbose_name='参考'),
        ),
    ]
