# Generated by Django 3.0.2 on 2020-06-30 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0004_recipe_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='quoted',
        ),
    ]
