# Generated by Django 3.0.2 on 2020-07-01 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eat', '0005_remove_recipe_quoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='quote_user',
            field=models.ManyToManyField(blank=True, related_name='quote_user', to=settings.AUTH_USER_MODEL, verbose_name='参考cookレシピ'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='quote_recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='quote_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_recipe_name', to='eat.Recipe'),
        ),
    ]
