# Generated by Django 3.0.2 on 2020-07-02 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eat', '0006_auto_20200701_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='quote',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quote_user',
            field=models.ManyToManyField(blank=True, related_name='quote_user', to=settings.AUTH_USER_MODEL, verbose_name='参考cookユーザー'),
        ),
    ]
