# Generated by Django 3.0.2 on 2020-07-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0008_auto_20200707_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quote_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('この投稿は消去されました'), related_name='quote_recipe_name', to='eat.Recipe'),
        ),
    ]
