# Generated by Django 3.0.2 on 2020-07-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0009_auto_20200707_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quote_recipe',
            field=models.ForeignKey(blank=True, default='無し', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_recipe_name', to='eat.Recipe'),
        ),
    ]
